INSERT INTO vk.communities (id, name, number_users) VALUES (1, 'Biological Products, Except Diagnostic Substances', 3);
INSERT INTO vk.communities (id, name, number_users) VALUES (2, 'Real Estate Agents and Managers', 8);
INSERT INTO vk.communities (id, name, number_users) VALUES (3, 'Adhesives and Sealants', 0);
INSERT INTO vk.communities (id, name, number_users) VALUES (4, 'Real Estate', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (5, 'Air and Gas Compressors', 2);
INSERT INTO vk.communities (id, name, number_users) VALUES (6, 'Fruit and Vegetable Markets', 5);
INSERT INTO vk.communities (id, name, number_users) VALUES (7, 'Household Audio And Video Equipment, And Audio', 7);
INSERT INTO vk.communities (id, name, number_users) VALUES (8, 'Automobiles and Other Motor Vehicles', 2);
INSERT INTO vk.communities (id, name, number_users) VALUES (9, 'Animal Specialty Services, Except Veterinary', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (10, 'Refined Petroleum Pipelines', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (11, 'Furniture', 6);
INSERT INTO vk.communities (id, name, number_users) VALUES (12, 'Rice', 4);
INSERT INTO vk.communities (id, name, number_users) VALUES (13, 'Paints, Varnishes, Lacquers, Enamels, and Allied Products', 3);
INSERT INTO vk.communities (id, name, number_users) VALUES (14, 'Logging', 3);
INSERT INTO vk.communities (id, name, number_users) VALUES (15, 'Liquor Stores', 7);
INSERT INTO vk.communities (id, name, number_users) VALUES (16, 'Foreign Banking And Branches And Agencies Of', 6);
INSERT INTO vk.communities (id, name, number_users) VALUES (17, 'Ferroalloy Ores, Except Vanadium', 8);
INSERT INTO vk.communities (id, name, number_users) VALUES (18, 'Motors and Generators', 1);
INSERT INTO vk.communities (id, name, number_users) VALUES (19, 'Executive Offices', 4);
INSERT INTO vk.communities (id, name, number_users) VALUES (20, 'Hotels, Rooming Houses, Camps, And Other Lodging Places', 4);
INSERT INTO vk.communities (id, name, number_users) VALUES (21, 'Theatrical Producers (Except Motion Picture) and Miscellaneous Theatrical Services', 10);
INSERT INTO vk.communities (id, name, number_users) VALUES (22, 'Frozen Specialties, Not Elsewhere Classified', 7);
INSERT INTO vk.communities (id, name, number_users) VALUES (23, 'Abrasive, Asbestos, And Miscellaneous', 3);
INSERT INTO vk.communities (id, name, number_users) VALUES (24, 'Furniture Stores', 8);
INSERT INTO vk.communities (id, name, number_users) VALUES (25, 'Office and Store Fixtures, Partitions, Shelving, and Lockers, Except Wood', 7);
INSERT INTO vk.communities (id, name, number_users) VALUES (26, 'Cigarettes', 4);
INSERT INTO vk.communities (id, name, number_users) VALUES (27, 'Cash Grains, Not Elsewhere Classified', 8);
INSERT INTO vk.communities (id, name, number_users) VALUES (28, 'Greeting Cards', 6);
INSERT INTO vk.communities (id, name, number_users) VALUES (29, 'Membership Organizations, Not Elsewhere Classified', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (30, 'Broiler, Fryer, and Roaster Chickens', 8);
INSERT INTO vk.communities (id, name, number_users) VALUES (31, 'Real Estate Investment Trusts', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (32, 'Paperboard Containers And Boxes', 5);
INSERT INTO vk.communities (id, name, number_users) VALUES (33, 'Wood Pallets and Skids', 5);
INSERT INTO vk.communities (id, name, number_users) VALUES (34, 'Speed Changers, Industrial High-Speed Drives, and Gears', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (35, 'Watches, Clocks, Clockwork Operated Devices, and Parts', 2);
INSERT INTO vk.communities (id, name, number_users) VALUES (36, 'Organization Hotels And Lodging Houses, On', 2);
INSERT INTO vk.communities (id, name, number_users) VALUES (37, 'Ferroalloy Ores, Except Vanadium', 5);
INSERT INTO vk.communities (id, name, number_users) VALUES (38, 'Mortgage Bankers and Loan Correspondents', 8);
INSERT INTO vk.communities (id, name, number_users) VALUES (39, 'Cigarettes', 7);
INSERT INTO vk.communities (id, name, number_users) VALUES (40, 'Public Order and Safety, Not Elsewhere Classified', 0);
INSERT INTO vk.communities (id, name, number_users) VALUES (41, 'Soybeans', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (42, 'Clay, Ceramic, And Refractory Minerals', 6);
INSERT INTO vk.communities (id, name, number_users) VALUES (43, 'Combination Utilities, Not Elsewhere Classified', 3);
INSERT INTO vk.communities (id, name, number_users) VALUES (44, 'Berry Crops', 5);
INSERT INTO vk.communities (id, name, number_users) VALUES (45, 'Vitreous China Plumbing Fixtures and China and Earthenware Fittings and Bathroom Accessories', 5);
INSERT INTO vk.communities (id, name, number_users) VALUES (46, 'Commodity Contracts Brokers and Dealers', 1);
INSERT INTO vk.communities (id, name, number_users) VALUES (47, 'Agricultural Production Crops', 0);
INSERT INTO vk.communities (id, name, number_users) VALUES (48, 'Dry, Condensed, and Evaporated Dairy Products', 9);
INSERT INTO vk.communities (id, name, number_users) VALUES (49, 'Functions Related To Depository Banking', 2);
INSERT INTO vk.communities (id, name, number_users) VALUES (50, 'Hosiery, Not Elsewhere Classified', 4);